Add option to update DockerC

diff --git a/dockerc b/dockerc
--- a/dockerc
+++ b/dockerc
@@ -11,6 +11,7 @@ VERSION="1.3.3"
 # Default options
 PRINT_HELP=false
 PRINT_VERSION=false
+UPDATE=false
 DRY_RUN=false
 QUIET=false
 
@@ -35,6 +36,11 @@ while true; do
 		--version)
 			# Print version and exit
 			PRINT_VERSION=true
+			shift
+			;;
+		--update)
+			# Update DockerC and exit
+			UPDATE=true
 			shift
 			;;
 		-n)
@@ -65,6 +71,7 @@ if [ "$PRINT_HELP" = true ]; then
 	echo "  options:"
 	echo "    -h, --help     Print this help and exit"
 	echo "    -v, --version  Print version and exit"
+	echo "    --update       Update DockerC and exit"
 	echo "    -n             Dry run, print docker compose command without running it"
 	echo "    -q             Quiet, do not print docker compose command"
 	exit 0
@@ -86,6 +93,26 @@ if [ "$PRINT_VERSION" = true ]; then
 
 	else
 		echo "v$VERSION"
+	fi
+
+	exit 0
+fi
+
+if [ "$UPDATE" = true ]; then
+	# Update DockerC and exit
+	INSTALL_DIR=$(dirname "$0")
+
+	if [ ! -d "$INSTALL_DIR" ]; then
+		echo "Error: Install directory does not exist."
+		exit 1
+	fi
+
+	if [ "$DRY_RUN" = false ]; then
+		echo "Updating DockerC..."
+		exec /bin/sh -c "curl -fsSL https://raw.githubusercontent.com/matiboux/dockerc/HEAD/install.sh | /bin/sh -s -- $INSTALL_DIR"
+	else
+		echo "Updating DockerC (dry run):"
+		echo "> curl -fsSL https://raw.githubusercontent.com/matiboux/dockerc/HEAD/install.sh | /bin/sh -s -- $INSTALL_DIR"
 	fi
 
 	exit 0
