Add docker presets help

diff --git a/dockerc b/dockerc
--- a/dockerc
+++ b/dockerc
@@ -162,6 +162,7 @@ fi
 # Check for docker preset
 if [ "${CONTEXT:0:1}" = "@" ]; then
 
+	PRINT_DOCKER_PRESETS_HELP=false
 	DOCKER_ARGS=""
 
 	# Remove first char
@@ -169,11 +170,21 @@ if [ "${CONTEXT:0:1}" = "@" ]; then
 
 	case "$CONTEXT" in
 
+		"")
+			PRINT_DOCKER_PRESETS_HELP=true
+			;;
+
 		"rfc")
 			DOCKER_ARGS="container prune -f"
 			;;
+		"rfca")
+			DOCKER_ARGS="container prune -f -a"
+			;;
 		"rfi")
 			DOCKER_ARGS="image prune -f"
+			;;
+		"rfia")
+			DOCKER_ARGS="image prune -f -a"
 			;;
 		"rf")
 			DOCKER_ARGS="system prune -f"
@@ -192,16 +203,34 @@ if [ "${CONTEXT:0:1}" = "@" ]; then
 
 	esac
 
+	if [ "$PRINT_DOCKER_PRESETS_HELP" = true ]; then
+		# Print help and exit
+		echo "Usage: $0 [options] @[preset] [...args]"
+		echo "  args: Arguments passed to docker compose"
+		echo "  presets:"
+		echo "    rfc   Remove unused containers"
+		echo "    rfca  Remove all unused containers"
+		echo "    rfi   Remove unused images"
+		echo "    rfia  Remove all unused images"
+		echo "    rf    Remove unused containers, networks and images"
+		echo "    rfa   Remove all unused containers, networks and images"
+		echo "    rfav  Remove all unused containers, networks, images and volumes"
+		echo "  options:"
+		echo "    -n   Dry run, print docker compose command without running it"
+		echo "    -q   Quiet, do not print docker compose command"
+		exit 0
+	fi
+
 	if [ "$QUIET" = false ]; then
 		# Print docker command
 		echo ""
-		echo "> docker $DOCKER_ARGS"
+		echo "> docker $DOCKER_ARGS $ARGS"
 		echo ""
 	fi
 
 	if [ "$DRY_RUN" = false ]; then
 		# Run docker
-		exec docker $DOCKER_ARGS
+		exec docker $DOCKER_ARGS $ARGS
 	fi
 
 	exit 0
@@ -384,6 +413,11 @@ if [ "${ARGS:0:1}" = "@" ]; then
 	fi
 
 	case "$ARGS_PRESET" in
+
+		"")
+			echo "Error: Empty args preset"
+			exit 1
+			;;
 
 		"u")
 			ARGS="up$ARGS"
